### ISSUE TITLE
Add a zoom feature

### ISSUE THREAD

**Issue by marco-zani** [scrivanolabs/ScrivanoForLinux#10]
Hi, first of all congratulation for your application, I love it. Secondly I think that Scrivano lacks a zoom feature, which can turn really useful when drawing graphs, schemes or just big documents who don't fit in a single page. Just something in the user case of: I'm writing, I want to get the bigger picture, I zoom out, get the idea, zoom in again and keep writing.
Thank you for your time and consideration

**Comment by scrivanolabs** [comment]
Hi what do you mean by zoom feature? You should be able to pinch to zoom on the screen to zoom in and out on the canvas.
Do you mean zooming using a mouse or a slider?

**Comment by marco-zani** [comment]
I guess this has turned out to be a bug, not a missing feature. I'm not able to pinch inside your application.

I'm using the flatpak version (0.15.4) on fedora (36) plasma (5.26.4) using wayland. 
What other info could help you?

**Comment by scrivanolabs** [comment]
Hi, I've tried to reproduce the problem using Fedora 37 and Gnome but wasn't able to. Does pinch to zoom work in other applications? 
Can you try to run Scrivano in X11 mode using Flatseal?

**Comment by marco-zani** [comment]
I'm not using GNOME, I'm using plasma (KDE), isn't the flatpak supposed to work without depending on the desktop environment?
BTW I also tried to run it using X11 without any result

**Comment by scrivanolabs** [comment]
I have also tried with a fresh installation of Fedora 36 KDE edition and I couldn't reproduce the problem. As I said, It'd be important to know whether you're able to use pinch to zoom in other application. You could try with Firefox, but it'd be best to try with the Flatpak version of Krita since it also relies on Qt (just like Scrivano).

>  isn't the flatpak supposed to work without depending on the desktop environment?

Yes and no. Flatpak provides a runtime for applications that can be execute in a containerised environment, but the behaviour of the apps still depend on the configuration of the system you're using.

**Comment by marco-zani** [comment]
Ok, I tried in krita and it also doesn't work, so I will try to work with Qt to understand what is going on, thank you for your support

Just one last thing I thought while experiencing this bug. I'm using a drawing tablet which only accepts his pen as an input. If a user uses this kind of tablets with a tower PC (basically without a touch pad), it wouldn't be able to zoom. I still think that having pinching as the only way to zoom would be lacking for this amazing application.

**Comment by scrivanolabs** [comment]
Ok, it seems that the issue you raised concerns pinch to zoom on a **touchpad** and *not* a touchscreen, right? That's not supported at the moment because it is not enabled in Qt 5. Eventually Scrivano will be upgraded to Qt 6 and then I'll try to enable support touchpad zooming.

However, pinch to zoom is not the only way to zoom. You can also zoom by holding the Ctrl key and scroll up/down with your mouse or touchpad.
