### ISSUE TITLE
Insert Space: On PDF Documents

### ISSUE THREAD

**Issue by MaasTL** [scrivanolabs/ScrivanoForLinux#13]
Insert Space is a great tool. And I'd love for it to work with PDF Documents.

My usecase:
I've got an PDF Document containing excercises.

What I want to do:
is Insert Space underneath an excercise to give me some space for writing my answer directly underneath it.

This would be wonderful!

**Comment by scrivanolabs** [comment]
Hi, in order to correctly exports documents the vertical space tool does not operate on PDF pages (for example you may end up with a situation where the PDF page is half-way between two pages). I can't really think of a good way to incorporate the vertical space tool without breaking the exporting functionality.

There are two things you can do to get extra space when importing PDFs:

1. Use a document size larger than the page size. This will center the PDF page on each page and give you extra margins where you can write.

2. You can insert an empty page by using the "Edit Pages" menu. This will allow you to write on a blank page after the exercise you want to complete.
